### ISSUE TITLE
 [ Silence ] issue

### ISSUE THREAD

**Issue by webnet918** [sakura6264/WhisperDesktop#3]
May I ask why the transcribed file is showing [ Silence ]? It was working fine for a long time, but today is the first time I encountered this issue. I have tried multiple times, but the generated VTT file still contains [ Silence ].

**Comment by arcana6264** [comment]
Maybe that is because the program split the audio into several pieces and then transcribes them into text.
If there is a piece is fully silent, the model will output [Silence] instead of output nothing.
