### ISSUE TITLE
runFullImpl: failed to generate timestamp token

### ISSUE THREAD

**Issue by mike22437120** [sakura6264/WhisperDesktop#4]
![微信图片_20240208173440](https://github.com/sakura6264/WhisperDesktop/assets/3660061/c697f97c-5e20-4671-8dc8-cd6b4e261139)
it was fine yesterday, but it reported an error today

**Comment by arcana6264** [comment]
Sorry, but I can't reproduce this error.
Sometime when the model can't recognize anything, it will skip 1s of the media and log "failed to generate timestamp token", and usually running the inference again may make it work again. 
So maybe there is something wrong with your input.

Or you could try [the official one](https://github.com/Const-me/Whisper), if it doesn't work either, you could create an issue there.

( I don't have a GPU which is good enough to use the large model, so I could only try to use the medium one for testing.)
